default_platform(:ios)

XCODE_PROJECT = "./ios/App/App.xcodeproj"
XCODE_WORKSPACE = "./ios/App/App.xcworkspace"
SCHEME = "App"

platform :ios do
  desc "[CI] Build the Apollon iOS app and produce an .ipa signed for the App Store"
  lane :build do
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)

    setup_ci(force: true)

    match(
      app_identifier: [app_identifier],
      type: "appstore",
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: ENV["MATCH_GITLAB_AUTH"],
      api_key: api_key,
      git_branch: "main",
      readonly: false
    )

    update_code_signing_settings(
      path: XCODE_PROJECT,
      use_automatic_signing: false,
      code_sign_identity: "iPhone Distribution",
      sdk: "iphoneos*",
      profile_name: "match AppStore #{app_identifier}",
      bundle_identifier: app_identifier,
      team_id: team_id
    )

    if ENV["MARKETING_VERSION"] && !ENV["MARKETING_VERSION"].empty?
      increment_version_number(
        version_number: ENV["MARKETING_VERSION"],
        xcodeproj: XCODE_PROJECT
      )
    end

    if ENV["BUILD_NUMBER"] && !ENV["BUILD_NUMBER"].empty?
      increment_build_number(
        build_number: ENV["BUILD_NUMBER"],
        xcodeproj: XCODE_PROJECT
      )
    end

    build_app(
      scheme: SCHEME,
      workspace: XCODE_WORKSPACE,
      clean: true,
      configuration: "Release",
      output_name: "App.ipa",
      output_directory: "./build",
      derived_data_path: ".DerivedData",
      export_options: {
        provisioningProfiles: {
          app_identifier => "match AppStore #{app_identifier}"
        }
      }
    )
  end

  desc "[CI] Upload the most recent build to TestFlight"
  lane :release do
    upload_to_testflight(
      ipa: "./build/App.ipa",
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  lane :api_key do
    app_store_connect_api_key(
      duration: 300,
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_KEY_ISSUER_ID"],
      key_content: ENV["API_KEY_PASSWORD"],
      is_key_content_base64: true
    )
  end
end
