changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
      - dependabot
  categories:
    - title: Features
      labels:
        - feat
        - enhancement
    - title: Bug fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Other changes
      labels:
        - "*"
