services:
  webapp:
    build:
      context: ..
      dockerfile: ./standalone/webapp/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - apollon2-local

  server:
    build:
      context: ..
      dockerfile: ./standalone/server/Dockerfile
    ports:
      - "8000:8000"
      - "4444:4444"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WS_PORT=4444
      - REDIS_URL=redis://db:6379
    depends_on:
      db:
        condition: service_healthy
    networks:
      - apollon2-local

  db:
    image: redis/redis-stack-server:7.4.0-v3
    ports:
      - "6379:6379"
    volumes:
      - dbdata:/data
    networks:
      - apollon2-local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:

networks:
  apollon2-local:
    driver: bridge
