import type { ReactNode } from "react"
import { Button } from "@tumaet/ui/components/button"
import NodeCreation from "assets/images/how-to-use-node-creation.png"
import EdgeCreation from "assets/images/how-to-use-edge-creation.png"
import NodeEdit from "assets/images/how-to-use-node-edit.png"
import NodeMove from "assets/images/how-to-use-node-move.png"

type HowToUseModalProps = {
  /** Called when the user dismisses the walkthrough via the Close button. */
  onClose: () => void
}

type Step = {
  title: string
  description: ReactNode
  /** Screenshot of the live editor (regenerated by how-to-use.visual.spec.ts). */
  image?: string
  alt?: string
}

// The screenshots are regenerated from the current editor and guarded by the
// `howto-assets` Playwright project — see tests/visual/how-to-use.visual.spec.ts.
const STEPS: Step[] = [
  {
    title: "Add Node",
    description:
      "Drag and drop one of the elements on the left side into the editor area.",
    image: NodeCreation,
    alt: "Dragging a palette element onto the canvas to create a node",
  },
  {
    title: "Add Edge",
    description:
      "Select the source class with a single click — blue circles appear around it marking the connection points. Click and hold one, then drag it to another node to create an edge.",
    image: EdgeCreation,
    alt: "Two class nodes connected by an association edge",
  },
  {
    title: "Edit Class",
    description:
      "Double-click a class to open its editor, where you can change its name, stereotype, attributes and methods.",
    image: NodeEdit,
    alt: "The class edit popover open beside a selected node",
  },
  {
    title: "Delete Class",
    description: (
      <>
        Select it with a single click and press <kbd>Delete</kbd> or{" "}
        <kbd>Backspace</kbd>.
      </>
    ),
  },
  {
    title: "Move Class",
    description:
      "Select it with a single click, then use the arrow keys or drag and drop it.",
    image: NodeMove,
    alt: "A selected class node showing its move and delete affordances",
  },
  {
    title: "Undo & Redo",
    description: (
      <>
        Press <kbd>Ctrl</kbd>+<kbd>Z</kbd> to undo and <kbd>Ctrl</kbd>+
        <kbd>Y</kbd> to redo your changes.
      </>
    ),
  },
]

export const HowToUseModal = ({ onClose }: HowToUseModalProps) => {
  return (
    <div className="flex flex-col gap-6 p-6 text-foreground">
      <ol className="flex flex-col gap-8">
        {STEPS.map((step) => (
          <li key={step.title} className="flex flex-col gap-2">
            <h5 className="text-base font-semibold">{step.title}</h5>
            <p className="text-sm text-muted-foreground [&_kbd]:rounded [&_kbd]:border [&_kbd]:border-border [&_kbd]:bg-muted [&_kbd]:px-1.5 [&_kbd]:py-0.5 [&_kbd]:font-mono [&_kbd]:text-xs [&_kbd]:text-foreground">
              {step.description}
            </p>
            {step.image && (
              <img
                src={step.image}
                alt={step.alt}
                loading="lazy"
                className="mt-1 block w-full rounded-lg border border-border"
              />
            )}
          </li>
        ))}
      </ol>
      <Button variant="default" onClick={onClose}>
        Close
      </Button>
    </div>
  )
}
