/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as PlaygroundRouteImport } from "./routes/playground"
import { Route as ImprintRouteImport } from "./routes/imprint"
import { Route as IdRouteImport } from "./routes/$id"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SharedDiagramIdRouteImport } from "./routes/shared.$diagramId"
import { Route as LocalIdRouteImport } from "./routes/local.$id"

const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: "/playground",
  path: "/playground",
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: "/imprint",
  path: "/imprint",
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SharedDiagramIdRoute = SharedDiagramIdRouteImport.update({
  id: "/shared/$diagramId",
  path: "/shared/$diagramId",
  getParentRoute: () => rootRouteImport,
} as any)
const LocalIdRoute = LocalIdRouteImport.update({
  id: "/local/$id",
  path: "/local/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$id": typeof IdRoute
  "/imprint": typeof ImprintRoute
  "/playground": typeof PlaygroundRoute
  "/privacy": typeof PrivacyRoute
  "/local/$id": typeof LocalIdRoute
  "/shared/$diagramId": typeof SharedDiagramIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$id": typeof IdRoute
  "/imprint": typeof ImprintRoute
  "/playground": typeof PlaygroundRoute
  "/privacy": typeof PrivacyRoute
  "/local/$id": typeof LocalIdRoute
  "/shared/$diagramId": typeof SharedDiagramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$id": typeof IdRoute
  "/imprint": typeof ImprintRoute
  "/playground": typeof PlaygroundRoute
  "/privacy": typeof PrivacyRoute
  "/local/$id": typeof LocalIdRoute
  "/shared/$diagramId": typeof SharedDiagramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$id"
    | "/imprint"
    | "/playground"
    | "/privacy"
    | "/local/$id"
    | "/shared/$diagramId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/$id"
    | "/imprint"
    | "/playground"
    | "/privacy"
    | "/local/$id"
    | "/shared/$diagramId"
  id:
    | "__root__"
    | "/"
    | "/$id"
    | "/imprint"
    | "/playground"
    | "/privacy"
    | "/local/$id"
    | "/shared/$diagramId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  ImprintRoute: typeof ImprintRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PrivacyRoute: typeof PrivacyRoute
  LocalIdRoute: typeof LocalIdRoute
  SharedDiagramIdRoute: typeof SharedDiagramIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/playground": {
      id: "/playground"
      path: "/playground"
      fullPath: "/playground"
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/imprint": {
      id: "/imprint"
      path: "/imprint"
      fullPath: "/imprint"
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$id": {
      id: "/$id"
      path: "/$id"
      fullPath: "/$id"
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/shared/$diagramId": {
      id: "/shared/$diagramId"
      path: "/shared/$diagramId"
      fullPath: "/shared/$diagramId"
      preLoaderRoute: typeof SharedDiagramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/local/$id": {
      id: "/local/$id"
      path: "/local/$id"
      fullPath: "/local/$id"
      preLoaderRoute: typeof LocalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  ImprintRoute: ImprintRoute,
  PlaygroundRoute: PlaygroundRoute,
  PrivacyRoute: PrivacyRoute,
  LocalIdRoute: LocalIdRoute,
  SharedDiagramIdRoute: SharedDiagramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
