// @ts-check
import globals from "globals"
import pluginJs from "@eslint/js"
import tseslint from "typescript-eslint"
import eslintReact from "@eslint-react/eslint-plugin"
import reactHooks from "eslint-plugin-react-hooks"

/** @type {import('eslint').Linter.Config[]} */
export default [
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "playwright-report/**",
      "test-results/**",
      "coverage/**",
      "storybook-static/**",
      // Capacitor native projects (contain generated/bundled web assets)
      "ios/**",
      "android/**",
      // Generated by the TanStack Router plugin (committed, not hand-edited).
      "src/routeTree.gen.ts",
    ],
  },
  { files: ["**/*.{js,ts,tsx}"] },
  { languageOptions: { globals: globals.browser } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  // recommended-typescript disables the prop-types rules TypeScript already enforces.
  eslintReact.configs["recommended-typescript"],
  {
    plugins: { "react-hooks": reactHooks },
    // eslint-plugin-react-hooks is the hooks / React-Compiler authority here;
    // turn off @eslint-react's overlapping hook-rule copies so each concern is
    // reported once, by react-hooks.
    rules: {
      ...reactHooks.configs.flat.recommended.rules,
      "@eslint-react/error-boundaries": "off",
      "@eslint-react/exhaustive-deps": "off",
      "@eslint-react/purity": "off",
      "@eslint-react/rules-of-hooks": "off",
      "@eslint-react/set-state-in-effect": "off",
      "@eslint-react/set-state-in-render": "off",
      "@eslint-react/static-components": "off",
      "@eslint-react/unsupported-syntax": "off",
      "@eslint-react/use-memo": "off",
      // Match library config: exhaustive-deps as warning.
      "react-hooks/exhaustive-deps": "warn",
      // The webapp is fully migrated off MUI/Emotion onto @tumaet/ui
      // (Base UI) + lucide-react. Ban re-introducing them.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@mui/*", "@mui"],
              message:
                "MUI is removed from the webapp. Use @tumaet/ui (Base UI) primitives and lucide-react icons instead.",
            },
            {
              group: ["@emotion/*", "@emotion"],
              message:
                "Emotion is removed from the webapp. Style with Tailwind utilities and the shared --apollon-*/--home-* tokens.",
            },
          ],
        },
      ],
    },
  },
  {
    // setState-in-effect is the correct pattern in these pre-existing sites —
    // async thumbnail loading, editor/diagram subscription sync, post-commit
    // list tracking, navbar title subscription, async legal-content fetch — so
    // it is warn here while staying an error everywhere else (new occurrences
    // outside this list still fail).
    files: [
      "src/components/home/DiagramCard.tsx",
      "src/components/home/DiagramGallery.tsx",
      "src/components/modals/TemplateThumbnail.tsx",
      "src/components/navbar/Navbar.tsx",
      // The navbar title subscription moved out of EditorHeader.tsx into its
      // own container hook (Phase 4 presentational/container split).
      "src/components/navbar/useDiagramTitle.ts",
      "src/components/navbar/MobileIslands.tsx",
      "src/components/versioning/VersionDrawer.tsx",
      "src/hooks/useRegionHost.ts",
      "src/pages/ApollonShared.tsx",
      "src/pages/LegalPage.tsx",
    ],
    rules: { "react-hooks/set-state-in-effect": "warn" },
  },
]
