name: Build and Push Docker Image

on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  build-and-push-workflow:
    name: ${{ matrix.name }}
    if: |
      github.actor != 'dependabot[bot]' &&
      (
        github.event_name == 'push' ||
        (github.event_name == 'pull_request' &&
         github.event.action == 'labeled' &&
         github.event.label.name == 'build and push docker image')
      )
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Webapp
            dockerfile: ./standalone/webapp/Dockerfile
            image: ghcr.io/ls1intum/apollon2/apollon-webapp
            context: .
          - name: Server
            dockerfile: ./standalone/server/Dockerfile
            image: ghcr.io/ls1intum/apollon2/apollon-server
            context: .
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ${{ matrix.image }}
      docker-file: ${{ matrix.dockerfile }}
      docker-context: ${{ matrix.context }}
