name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: "Image tag to deploy (default: latest for main branch)"
      deploy-app:
        type: boolean
        default: true
        description: (Re-)deploy server + webapp
      deploy-db:
        type: boolean
        default: false
        description: (Re-)deploy Redis database. Usually not necessary.
      deploy-proxy:
        type: boolean
        default: false
        description: (Re-)deploy Caddy proxy. Usually not necessary.

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy-db:
    if: ${{ inputs.deploy-db }}
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: Production
      docker-compose-file: "./docker/compose.db.yml"
      main-image-name: redis
      image-tag: 7-alpine
      deployment-base-path: "/opt/apollon/db"
    secrets: inherit

  deploy-proxy:
    if: ${{ inputs.deploy-proxy }}
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: Production
      docker-compose-file: "./docker/compose.proxy.yml"
      main-image-name: caddy
      image-tag: 2.9-alpine
      deployment-base-path: "/opt/apollon/proxy"
    secrets: inherit

  deploy-app:
    if: ${{ inputs.deploy-app }}
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: Production
      docker-compose-file: "./docker/compose.app.yml"
      main-image-name: ghcr.io/ls1intum/apollon2/apollon-server
      image-tag: ${{ inputs.image-tag }}
      deployment-base-path: "/opt/apollon/app"
    secrets: inherit
